from numpy.typing import NDArray

class LMSFilter:
    def __init__(self, mu: float, window_size: int) -> None: ...
    @property
    def window_size(self) -> int: ...
    def adapt(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...
    def filter(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...

class NLMSFilter:
    def __init__(self, mu: float, eps: float, window_size: int) -> None: ...
    @property
    def window_size(self) -> int: ...
    def adapt(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...
    def filter(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...

class RLSFilter:
    def __init__(
        self, forgetting_factor: float, delta: float, window_size: int
    ) -> None: ...
    @property
    def window_size(self) -> int: ...
    def adapt(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...
    def filter(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...

class BlockLMSFilter:
    def __init__(self, mu: float, window_size: int, block_size: int) -> None: ...
    @property
    def window_size(self) -> int: ...
    @property
    def block_size(self) -> int: ...
    def adapt(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...
    def filter(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...
