from numpy.typing import NDArray

class LMSFilter:
    def __init__(self, mu: float, window_size: int) -> None: ...
    @staticmethod
    def from_weights(mu: float, weights: NDArray) -> LMSFilter: ...
    @property
    def window_size(self) -> int: ...
    @property
    def weights(self) -> NDArray: ...
    def adapt(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...
    def filter(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...

class NLMSFilter:
    def __init__(self, mu: float, eps: float, window_size: int) -> None: ...
    @staticmethod
    def from_weights(mu: float, eps: float, weights: NDArray) -> NLMSFilter: ...
    @property
    def window_size(self) -> int: ...
    @property
    def weights(self) -> NDArray: ...
    def adapt(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...
    def filter(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...

class RLSFilter:
    def __init__(
        self, forgetting_factor: float, p_init_scale: float, window_size: int
    ) -> None: ...
    @staticmethod
    def from_weights(
        forgetting_factor: float, p_init_scale: float, weights: NDArray
    ) -> RLSFilter: ...
    @property
    def window_size(self) -> int: ...
    @property
    def weights(self) -> NDArray: ...
    def adapt(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...
    def filter(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...

class BlockLMSFilter:
    def __init__(self, mu: float, window_size: int, block_size: int) -> None: ...
    @staticmethod
    def from_weights(
        mu: float, weights: NDArray, block_size: int
    ) -> BlockLMSFilter: ...
    @property
    def window_size(self) -> int: ...
    @property
    def block_size(self) -> int: ...
    @property
    def weights(self) -> NDArray: ...
    def adapt(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...
    def filter(self, input_signal: NDArray, noise_ref: NDArray) -> NDArray: ...
