name: Rust CI

on:
  push:
    paths:
      - "src/**"
      - "tests/rust/**"
      - ".github/workflows/rust-ci.yml"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/integration-ci.yml"
      - "rust-toolchain.toml"
      - "tests/setup_integration_data.py"
  pull_request:
    paths:
      - "src/**"
      - "tests/rust/**"
      - ".github/workflows/rust-ci.yml"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/integration-ci.yml"
      - "rust-toolchain.toml"
      - "tests/setup_integration_data.py"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust - latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust
        run: |
          rustup toolchain install 
          rustup component add rustfmt clippy

      - name: rust-cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cargo audit
        run: cargo binstall cargo-audit --no-confirm

      - name: Format code
        run: cargo fmt --all

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -Dwarnings

      - name: Build
        run: cargo build --verbose

      - name: Run unit tests
        run: cargo test --lib --verbose

      - name: Restore integration data
        uses: actions/cache@v4
        with:
          path: tests/data
          key: integration-data-v1-${{ hashFiles('tests/setup_integration_data.py') }}

      - name: Run integration tests
        run: cargo test --test rust --frozen

      - name: Audit dependencies
        run: cargo audit

  coverage:
    if: github.event_name == 'pull_request'
    name: Rust coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install latest Rust version
        run: rustup toolchain install

      - name: rust-cache
        uses: Swatinem/rust-cache@v2

      - name: Restore integration data
        uses: actions/cache@v4
        with:
          path: tests/data
          key: integration-data-v1-${{ hashFiles('tests/setup_integration_data.py') }}

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cargo tarpaulin
        run: cargo binstall cargo-tarpaulin --no-confirm

      - name: Run code coverage
        run: cargo tarpaulin --fail-under 70
